

# config/packages/security.yaml
security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
##security:
#    encoders:
#       App\Entity\User:
#        algorithm: auto
#
#    providers:
#        in_memory: { memory: ~ }
#        in_database:
#            entity:
 #               class: src\Entity\Users
 #               property: mail
#

#    provider:     in_memory
 #   firewalls:
#        main:
 #           pattern: ^/
 #           anonymous: true
#            provider: in_database
 #           form_login:
 #               login_path: connexion
 #               check_path: connexion
 #           logout:
 #               path: logout
 #               target: login